name: python-data
channels:
  - defaults
dependencies:
  - _tflow_select=2.2.0=eigen
  - absl-py=0.5.0=py36_0
  - astor=0.7.1=py36_0
  - blas=1.0=mkl
  - bokeh=1.0.0=py36_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py36_0
  - cycler=0.10.0=py36h009560c_0
  - freetype=2.9.1=ha9979f8_1
  - gast=0.2.0=py36_0
  - grpcio=1.12.1=py36h1a1b453_0
  - h5py=2.8.0=py36h3bdd7fb_2
  - hdf5=1.10.2=hac2f561_1
  - icc_rt=2017.0.4=h97af966_0
  - icu=58.2=ha66f8fd_1
  - intel-openmp=2019.0=118
  - jinja2=2.10=py36_0
  - jpeg=9b=hb83a4c4_2
  - keras=2.2.4=0
  - keras-applications=1.0.6=py36_0
  - keras-base=2.2.4=py36_0
  - keras-preprocessing=1.0.5=py36_0
  - kiwisolver=1.0.1=py36h6538335_0
  - libpng=1.6.35=h2a8f88b_0
  - libprotobuf=3.6.0=h1a1b453_0
  - libtiff=4.0.9=h36446d0_2
  - markdown=3.0.1=py36_0
  - markupsafe=1.0=py36hfa6e2cd_1
  - matplotlib=3.0.1=py36hc8f65d3_0
  - mkl=2019.0=118
  - mkl_fft=1.0.6=py36hdbbee80_0
  - mkl_random=1.0.1=py36h77b88f5_1
  - numpy=1.15.3=py36ha559c80_0
  - numpy-base=1.15.3=py36h8128ebf_0
  - olefile=0.46=py36_0
  - openssl=1.0.2p=hfa6e2cd_0
  - packaging=18.0=py36_0
  - pandas=0.23.4=py36h830ac7b_0
  - patsy=0.5.0=py36_0
  - pillow=5.3.0=py36hdc69c19_0
  - pip=10.0.1=py36_0
  - protobuf=3.6.0=py36he025d50_0
  - pyparsing=2.2.2=py36_0
  - pyqt=5.9.2=py36h6538335_2
  - python=3.6.7=h33f27b4_0
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.5=py36_0
  - pyyaml=3.13=py36hfa6e2cd_0
  - qt=5.9.6=vc14h1e9a669_2
  - scikit-learn=0.20.0=py36heebcf9a_1
  - scipy=1.1.0=py36h4f6bf74_1
  - seaborn=0.9.0=py36_0
  - setuptools=40.4.3=py36_0
  - sip=4.19.8=py36h6538335_0
  - six=1.11.0=py36_1
  - sqlalchemy=1.2.12=py36he774522_0
  - sqlite=3.25.2=hfa6e2cd_0
  - statsmodels=0.9.0=py36h452e1ab_0
  - tensorboard=1.11.0=py36he025d50_0
  - tensorflow=1.11.0=eigen_py36h346fd36_0
  - tensorflow-base=1.11.0=eigen_py36h45df0d8_0
  - termcolor=1.1.0=py36_1
  - tk=8.6.8=hfa6e2cd_0
  - tornado=5.1.1=py36hfa6e2cd_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.32.2=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - yaml=0.1.7=hc54c509_2
  - zlib=1.2.11=h8395fce_2
prefix: C:\Users\s4d-asus-14\Anaconda3\envs\python-data

